# Generated by Django 4.0.1 on 2022-01-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_cliente_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(default='', max_length=300),
        ),
    ]
