# Generated by Django 4.0.1 on 2022-01-20 13:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_itempedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='valor_item',
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.produto'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
