# Generated by Django 4.0.1 on 2022-01-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_remove_itempedido_valor_item_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together={('pedido', 'produto')},
        ),
    ]
